language: node_js

node_js:
  - "node"
  - "7.2"
  - "6.9"
  - "5.12"
  - "4.4"
  - "iojs"
  - "0.12"

addons:
  code_climate:
    repo_token: 0bc4f040eb2e410552e061cb003eaef5ea1f05d23f2dec59604f2ae5cb4eb841

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
