language: node_js
node_js:
  - "5.3"
  - "4.2"
  - "4.0"
  - "0.12"
  - "iojs"
  - "node"
#addons:
#  code_climate:
#    repo_token: 945b7fe507f4be6d6873671f4f6df377b90e0a1c4dc6cf18bf8a4680866a3a79
after_script:
  - npm run coverage
#  - codeclimate-test-reporter < coverage/lcov.info